services:
  api:
    image: ebenezer-backend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - database
    environment:
      - ArangoDb__User=root
      - ArangoDb__Password=${ARANGO_ROOT_PASSWORD}
      - ArangoDb__Host=database

  database:
    image: arangodb:3.12.7.1
    container_name: arangodb
    platform: linux/arm64/v8
    ports:
      - "${DB_PORT}:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
    volumes:
      - arangodb_data:/var/lib/arangodb3

volumes:
  arangodb_data: